/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyServerStatusIcons {
  MyServerStatusIcons._();

  static const _kFontFam = 'MyServerStatusIcons';
  static const String? _kFontPkg = null;

  static const IconData software = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storage = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlePlay = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memory = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
