/// Flutter icons OSIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OSIcons
///      fonts:
///       - asset: fonts/OSIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class OSIcons {
  OSIcons._();

  static const _kFontFam = 'OSIcons';
  static const String? _kFontPkg = null;

  static const IconData macos = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows = IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux = IconData(0xf17c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freebsd = IconData(0xf3a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
